name: Atualizar projetos recentes no README

on:
  workflow_dispatch:
  schedule:
    - cron: '0 */2 * * *' # roda a cada 2 horas
  push:
    branches:
      - main

permissions:
  contents: write

jobs:
  update-readme:
    runs-on: ubuntu-latest

    steps:
      - name: Clonar repositório
        uses: actions/checkout@v4

      - name: Buscar 3 repositórios mais recentes
        id: repos
        uses: actions/github-script@v7
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          script: |
            const username = 'felipeamlozano-ui';
            const { data: repos } = await github.rest.repos.listForUser({
              username,
              sort: 'updated',
              direction: 'desc',
              per_page: 3
            });

            const projectsHTML = `
<p align="center">
${repos.map(repo => `
  <a href="${repo.html_url}" target="_blank" style="margin: 10px;">
    <img src="https://opengraph.githubassets.com/1/${repo.full_name}" width="250px" height="140px" style="border-radius:10px;"/>
    <br/>
    <b>${repo.name}</b><br/>
    <sub>${repo.description || 'Sem descrição ainda.'}</sub>
  </a>
`).join('')}
</p>
`;

            // Exporta o HTML como output para o próximo step
            core.setOutput("projects", projectsHTML);

      - name: Atualizar README.md
        run: |
          section="${{ steps.repos.outputs.projects }}"
          # Substitui a seção entre os marcadores
          sed -i '/<!-- start-projects -->/,/<!-- end-projects -->/c<!-- start-projects -->\n'"$section"'\n<!-- end-projects -->' README.md

      - name: Commitar e enviar alterações (se houver)
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git add README.md
          if git diff --cached --quiet; then
            echo "✅ Nenhuma alteração para commitar"
          else
            git commit -m "🔄 Atualização automática dos últimos projetos"
            git push
          fi
