name: Atualizar projetos recentes no README

on:
  workflow_dispatch:
  schedule:
    - cron: '0 */12 * * *' # roda a cada 12 horas
  push:
    branches:
      - main

permissions:
  contents: write

jobs:
  update-readme:
    runs-on: ubuntu-latest

    steps:
      - name: Clonar repositório
        uses: actions/checkout@v4
        with:
          persist-credentials: true

      - name: Buscar 3 repositórios mais recentes e atualizar README
        uses: actions/github-script@v7
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          script: |
            const username = 'felipeamlozano-ui';
            const fs = require('fs');
            const path = 'README.md';

            // Pega os 3 repositórios mais recentemente atualizados
            const { data: repos } = await github.rest.repos.listForUser({
              username,
              sort: 'updated',
              direction: 'desc',
              per_page: 3
            });

            if (!fs.existsSync(path)) {
              throw new Error('README.md não encontrado na raiz do repositório.');
            }

            let readme = fs.readFileSync(path, 'utf8');

            // Gera a seção de projetos
            const projectsSection = `## Meus Projetos Recentes

<!-- start-projects -->
${repos.map(repo => 
`### 🔹 [${repo.name}](${repo.html_url})
${repo.description ? repo.description : '_Sem descrição ainda._'}

![Preview](https://opengraph.githubassets.com/1/${repo.full_name})

`).join('\n')}
<!-- end-projects -->
`;

            // Substitui ou adiciona a seção no README
            if (readme.includes('<!-- start-projects -->') && readme.includes('<!-- end-projects -->')) {
              const updated = readme.replace(
                /<!-- start-projects -->[\s\S]*<!-- end-projects -->/m,
                projectsSection
              );
              if (updated !== readme) {
                fs.writeFileSync(path, updated, 'utf8');
                console.log('README atualizado com os últimos projetos.');
              } else {
                console.log('Nenhuma mudança detectada no README.');
              }
            } else {
              readme += '\n\n' + projectsSection;
              fs.writeFileSync(path, readme, 'utf8');
              console.log('Adicionada nova seção de projetos no README.');
            }

      - name: Commitar e enviar alterações (se houver)
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git add README.md
          if git diff --cached --quiet; then
            echo "✅ Nenhuma alteração para commitar"
          else
            git commit -m "🔄 Atualização automática dos últimos projetos"
            git push
          fi
